# Generated by Django 5.0.3 on 2024-04-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("certificate", models.CharField(max_length=50)),
                ("runtime", models.CharField(max_length=50)),
                ("imdb", models.FloatField()),
                ("overview", models.TextField()),
                ("meta_score", models.IntegerField()),
                ("director", models.CharField(max_length=100)),
                ("actor1", models.CharField(max_length=100)),
                ("actor2", models.CharField(max_length=100)),
                ("actor3", models.CharField(max_length=100)),
                ("actor4", models.CharField(max_length=100)),
                ("votes", models.IntegerField()),
                ("gross", models.IntegerField()),
                ("genre", models.ManyToManyField(to="landing_page.genre")),
            ],
        ),
    ]
