# Generated by Django 5.0.3 on 2024-04-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0002_alter_movie_gross"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="actor1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="actor2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="actor3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="actor4",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="certificate",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="meta_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="overview",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="votes",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
